name: Build APK for Android 4.4

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install build dependencies
      - name: Install dependencies
        run: |
          pip install kivy pyinstaller

      - name: Building EXE
        run: |
            pyinstaller --onefile main.py
