name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv
          pip3 install --user -r requirements.txt
          pip3 install buildozer
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK Licenses
        run: yes 'y' | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK Build Tools
        run: sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0"  # Используем стабильную версию

      - name: Check Aidl
        run: |
          if [ -d "${ANDROID_HOME}/build-tools/36.0.0" ]; then
            echo "Build Tools found!"
            if [ -f "${ANDROID_HOME}/build-tools/36.0.0/aidl" ]; then
              echo "Aidl found!"
            else
              echo "Aidl not found in build-tools!"
              exit 1
            fi
          else
            echo "Build Tools not found!"
            exit 1
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/myapp-*-debug.apk
