name: Build APK for Android 4.4

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Шаг 2: Устанавливаем зависимости для сборки
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev build-essential git
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install buildozer

      # Шаг 3: Устанавливаем зависимости для Android
      - name: Install Android dependencies
        run: |
          sudo apt install -y openjdk-8-jdk
          sudo apt install -y zipalign
          sudo apt install -y adb
          sudo apt install -y libncurses5 libstdc++6 lib32z1 lib32ncurses5
          sudo apt install -y lib32stdc++6

      # Шаг 4: Устанавливаем Android SDK и NDK
      - name: Install Android SDK and NDK
        run: |
          # Устанавливаем Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d $HOME/android-sdk
          rm commandlinetools-linux-7302050_latest.zip
          
          # Устанавливаем необходимые компоненты SDK
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-19" "build-tools;29.0.3" "ndk;21.3.6528147"

      # Шаг 5: Принятие лицензий для SDK и NDK
      - name: Accept SDK/NDK licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager "ndk-bundle"

      # Шаг 6: Собираем APK
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug deploy run

      # Шаг 7: Архивируем APK файл
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
