name: Build APK for Android 4.4

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev build-essential git
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install buildozer
          pip install cython
          
      # Step 4: Install Android dependencies
      - name: Install Android dependencies
        run: |
          sudo apt install -y openjdk-8-jdk
          sudo apt install -y zipalign
          sudo apt install -y adb
          sudo apt install -y libstdc++6 lib32z1

      # Step 5: Install Android SDK and NDK
      - name: Install Android SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip # Пример старой версии
          
          unzip commandlinetools-linux-6609375_latest.zip -d $HOME/android-sdk-zip
          
          rm commandlinetools-linux-6609375_latest.zip
          
          mkdir -p $HOME/android-sdk/tools/latest
          mv $HOME/android-sdk-zip/tools/* $HOME/android-sdk/tools/latest/

          # Принимаем лицензии (обязательно перед установкой компонентов)
          yes | $HOME/android-sdk/tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses

          # Устанавливаем необходимые компоненты SDK
          yes | $HOME/android-sdk/tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-19" "build-tools;19.1.0" "ndk;19.2.5345600" # Заменил версии
          
      # Step 6: Build APK
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug deploy run

      # Step 7: Archive APK file
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
