name: Build APK for Android 4.4

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev build-essential git
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install buildozer

      # Step 4: Install Android dependencies
      - name: Install Android dependencies
        run: |
          sudo apt install -y openjdk-8-jdk
          sudo apt install -y zipalign
          sudo apt install -y adb
          sudo apt install -y libstdc++6 lib32z1

      # Step 5: Install Android SDK and NDK
      - name: Install Android SDK and NDK
        run: |
          # Download and extract Android command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d $HOME/android-sdk
          rm commandlinetools-linux-7302050_latest.zip

          # Create the expected directory structure for cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/path1
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools
          rmdir $HOME/android-sdk/cmdline-tools/path2

          # Install required SDK components with explicit SDK root
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-19" "build-tools;29.0.3" "ndk;21.3.6528147"

      # Step 6: Accept SDK/NDK licenses
      - name: Accept SDK/NDK licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "ndk-bundle"

      # Step 7: Build APK
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug deploy run

      # Step 8: Archive APK file
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
