name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK for Android
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: ${{ steps.buildozer.outputs.filename }}
